### ISSUE TITLE
Upstream License Changes

### ISSUE THREAD

**Issue by 151044** [OmnifactoryDevs/DimensionalEdibles#14]
The original author of the mod has changed the license from LGPL to a stricter one 5 days ago in this commit (https://github.com/JackyyTV/DimensionalEdibles/commit/4d2b8007913c94682b1a8d1ef412bd6495957d80).
In particular, this line
> You ***can't***:
> Redistribute an unofficial or modified version of this mod to the public.

might affect future distribution of this fork to Omnifactory players in the next version.

**Comment by serenibyss** [comment]
I am not a lawyer, but since this code was forked when it had an LGPL 3.0 License, this new licensing change cannot be retroactively applied to previous versions of the code base. It would probably be a good idea to change the name though.

Since the license has changed, its probably a good idea to mention in the README that this project was forked when the license was LGPL 3.0, and it can be proven by git history.

**Comment by Exaxxion** [comment]
There should be no need to clarify things on our end. We are compliant with the LGPL-licensed DimensionalEdibles code we forked from. Jackyy can change his own license going forward, but one cannot rescind the license from code already published under LGPL.

The ramifications of this are that we cannot make use of changes from the original repository following that commit, and Jackyy cannot make use of ours as he would no longer be compliant with the terms of this project's LGPLv3 license.
