### ISSUE TITLE
[Feature Request] Allow custom cakes to send the player to the same coords in the custom dimension

### ISSUE THREAD

**Issue by Caedis** [OmnifactoryDevs/DimensionalEdibles#29]
Currently, the only option is to have the cake send to custom coords which is problematic for servers.
Would it be possible to add an option to allow it to act like the nether cake where it sends the player to same coords as the cake in the target dimension?

**Comment by Exaxxion** [comment]
I can see how something along those lines would be useful for servers. I think that would be possible to implement.

**Comment by RickAstly** [comment]
its coord(inates) not chord(inates), sry but this annoys me

**Comment by Mixu78** [comment]
I think the custom cake should be deprecated and a real void cake be added. This fork was made specifically for Nomifactory, and it is a bit odd that the custom cake is used for teleporting into an externally added dimension instead of an inbuilt cake being used that would create the dimension if necessary and then teleport players to a position in the void dimenstion relative to the origin cake.

**Comment by Exaxxion** [comment]
Creating and managing custom dimensions is outside of the scope of what this mod does. With all of our forks, the idea is to offer extended support while maintaining compatibility with the original mod so that it is a simple matter to switch. We already use another mod that implements the capabilities we need for managing custom dimensions.

**Comment by Caedis** [comment]
What changes do you think are needed? I can start work on it now to help ease your workload.

**Comment by Exaxxion** [comment]
I haven't planned it out in particular detail, but roughly speaking I can see this needing its own NBT field on the custom cake class, and alternative placement logic would need to be implemented and used when the field indicates.

One complication I could see is players being able to use the cake from various dimensions would potentially allow griefing if we were to simply do a 1:1 same-coords teleport. Not sure what the best way to prevent that would be.

**Comment by Caedis** [comment]
Right, also have to think how these changes could affect a server with multiple players

**Comment by Mixu78** [comment]
A 1:1 teleport would be just fine, grief-preventing mods such as FTBUtilities with its teams and claims can be used alongside this mod for preventing grief if necessary.

**Comment by Exaxxion** [comment]
What I'm worried about is that cakes create a spawn platform of obsidian when you reach your destination, which could potentially bypass those types of restrictions and damage the destination.

It's not guaranteed to be a problem, but something I am concerned about and want to ensure isn't a problem.

**Comment by Mixu78** [comment]
The cake obsidian platform implementation could perhaps be changed so that the obsidian isn't placed within x blocks of already existing blocks?
